export const INITIAL_COMPLAINTS = [
  {
    id: "JS-2026-001245",
    title: "Hazardous Deep Pothole near City High School",
    category: "Road & Infrastructure",
    subcategory: "Potholes & Cavities",
    description: "Dangerous deep pothole right at the entrance of City High School causing severe traffic bottleneck and risk to students during school pick-up.",
    photoUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80",
    locationName: "Main Gate, City High School, MG Road, Ward 12",
    lat: 19.0760,
    lng: 72.8777,
    ward: "Ward 12 (Central Zone)",
    department: "Public Works Department (PWD)",
    assignedOfficer: "Rajesh Kumar (Senior PWD Inspector)",
    officerPhone: "+91 98201 44512",
    priorityLevel: "HIGH",
    priorityScore: 92,
    severity: "CRITICAL",
    confidence: 94,
    keywords: ["Pothole", "Asphalt Damage", "Traffic Risk", "High Severity"],
    corroborations: 14,
    status: "CITIZEN_VERIFICATION",
    slaHoursTotal: 48,
    slaHoursRemaining: 8,
    slaBreached: false,
    createdAt: "2026-08-14T10:30:00Z",
    updatedAt: "2026-08-16T09:15:00Z",
    resolution: {
      afterPhotoUrl: "https://images.unsplash.com/photo-1584467735871-8e85353a8413?auto=format&fit=crop&w=800&q=80",
      remarks: "Cold mix asphalt laying completed and heavy roller compaction executed. Area cleared for traffic.",
      completedAt: "2026-08-16T09:00:00Z",
      submittedBy: "Rajesh Kumar (PWD)",
      verifiedByCitizen: null
    },
    timeline: [
      { status: "REPORTED", title: "Complaint Logged", text: "Citizen submitted issue with photo evidence.", timestamp: "Aug 14, 10:30 AM", actor: "Citizen (Amit Verma)" },
      { status: "AI ANALYZING", title: "AI Classification Complete", text: "Category identified as Road Pothole (94% confidence). High Priority assigned.", timestamp: "Aug 14, 10:31 AM", actor: "Jan Sanket AI Engine" },
      { status: "ROUTED", title: "Routed to PWD", text: "Automatically routed to Ward 12 Public Works Department.", timestamp: "Aug 14, 10:31 AM", actor: "Automated Jurisdiction Engine" },
      { status: "ASSIGNED", title: "Officer Assigned", text: "Assigned to Field Inspector Rajesh Kumar.", timestamp: "Aug 14, 11:15 AM", actor: "Executive Engineer (Ward 12)" },
      { status: "IN_PROGRESS", title: "On-Site Repair Commenced", text: "Road patch repair crew dispatched with asphalt mixer.", timestamp: "Aug 15, 08:30 AM", actor: "Field Officer (Rajesh Kumar)" },
      { status: "RESOLUTION_SUBMITTED", title: "Resolution Evidence Uploaded", text: "Repair finished. Before/After photo evidence submitted for citizen sign-off.", timestamp: "Aug 16, 09:15 AM", actor: "Field Officer (Rajesh Kumar)" }
    ]
  },
  {
    id: "JS-2026-001246",
    title: "Overflowing Community Garbage Bin",
    category: "Sanitation & Waste Management",
    subcategory: "Waste Accumulation",
    description: "Bin has not been emptied for 3 days. Waste spreading across sidewalk causing foul smell and stray animal gathering.",
    photoUrl: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80",
    locationName: "Market Road Crossing, Ward 8",
    lat: 19.0820,
    lng: 72.8840,
    ward: "Ward 8 (North Zone)",
    department: "Solid Waste Management (SWM)",
    assignedOfficer: "Sanjay Patil (Sanitation Supervisor)",
    officerPhone: "+91 98330 11982",
    priorityLevel: "HIGH",
    priorityScore: 88,
    severity: "HIGH",
    confidence: 96,
    keywords: ["Garbage", "Waste", "Sanitation Hazard", "Public Health"],
    corroborations: 9,
    status: "IN_PROGRESS",
    slaHoursTotal: 24,
    slaHoursRemaining: -4,
    slaBreached: true,
    createdAt: "2026-08-15T07:15:00Z",
    updatedAt: "2026-08-16T08:00:00Z",
    resolution: null,
    timeline: [
      { status: "REPORTED", title: "Complaint Logged", text: "Issue submitted by citizen.", timestamp: "Aug 15, 07:15 AM", actor: "Citizen (Pooja Sharma)" },
      { status: "AI ANALYZING", title: "AI Classification", text: "Sanitation & Waste accumulation detected.", timestamp: "Aug 15, 07:16 AM", actor: "Jan Sanket AI Engine" },
      { status: "ASSIGNED", title: "Assigned to SWM Ward 8", text: "Supervisor Sanjay Patil tasked with compactor truck dispatch.", timestamp: "Aug 15, 08:00 AM", actor: "SWM Admin" },
      { status: "SLA_BREACHED", title: "SLA Deadline Breached", text: "24-hour SLA expired. Auto-escalated to Zonal Sanitation Officer.", timestamp: "Aug 16, 07:15 AM", actor: "SLA Monitor System" }
    ]
  },
  {
    id: "JS-2026-001247",
    title: "Non-Functional Streetlights along Lake View Avenue",
    category: "Electrical & Lighting",
    subcategory: "Street Light Outage",
    description: "Series of 5 consecutive streetlights out for past 2 nights, creating dark corridor and safety concern for pedestrians.",
    photoUrl: "https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80",
    locationName: "Lake View Avenue, Pole #42-47, Ward 4",
    lat: 19.0680,
    lng: 72.8650,
    ward: "Ward 4 (West Zone)",
    department: "Electrical Department",
    assignedOfficer: "Unassigned",
    officerPhone: "",
    priorityLevel: "MEDIUM",
    priorityScore: 65,
    severity: "MEDIUM",
    confidence: 91,
    keywords: ["Dark Street", "Lighting Outage", "Safety"],
    corroborations: 3,
    status: "ROUTED",
    slaHoursTotal: 72,
    slaHoursRemaining: 54,
    slaBreached: false,
    createdAt: "2026-08-16T02:00:00Z",
    updatedAt: "2026-08-16T02:05:00Z",
    resolution: null,
    timeline: [
      { status: "REPORTED", title: "Complaint Logged", text: "Reported by resident.", timestamp: "Aug 16, 02:00 AM", actor: "Citizen (Rohan Mehta)" },
      { status: "ROUTED", title: "Routed to Electrical Wing", text: "Waiting for supervisor assignment.", timestamp: "Aug 16, 02:05 AM", actor: "Jan Sanket Router" }
    ]
  },
  {
    id: "JS-2026-001248",
    title: "Burst Pipeline Leaking Drinking Water",
    category: "Water Supply & Sewage",
    subcategory: "Pipe Burst",
    description: "Clean water leaking rapidly from main supply junction, flooding road surface and wasting municipal water.",
    photoUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=800&q=80",
    locationName: "Subhash Nagar 3rd Cross, Ward 3",
    lat: 19.0910,
    lng: 72.8710,
    ward: "Ward 3 (East Zone)",
    department: "Water Supply & Hydro Utility",
    assignedOfficer: "Vikram Shah (Hydro Tech Lead)",
    officerPhone: "+91 97112 88390",
    priorityLevel: "HIGH",
    priorityScore: 95,
    severity: "CRITICAL",
    confidence: 97,
    keywords: ["Water Burst", "Resource Waste", "Hydro Hazard"],
    corroborations: 21,
    status: "RESOLVED",
    slaHoursTotal: 12,
    slaHoursRemaining: 12,
    slaBreached: false,
    createdAt: "2026-08-13T14:00:00Z",
    updatedAt: "2026-08-14T11:00:00Z",
    resolution: {
      afterPhotoUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80",
      remarks: "Replacement clamp installed on 300mm GI pipe. Main valve repressurized safely.",
      completedAt: "2026-08-14T09:30:00Z",
      submittedBy: "Vikram Shah",
      verifiedByCitizen: "CONFIRMED"
    },
    timeline: [
      { status: "REPORTED", title: "Complaint Logged", text: "Urgent report logged.", timestamp: "Aug 13, 02:00 PM", actor: "Citizen (Sunil Joshi)" },
      { status: "RESOLVED", title: "Issue Confirmed Resolved", text: "Citizen inspected location and confirmed zero leakage.", timestamp: "Aug 14, 11:00 AM", actor: "Citizen (Sunil Joshi)" }
    ]
  }
];
